horizon: 24
timestep: 1
add_unbalanced_module: true
loss_load_cost: 10
overgeneration_cost: 2
components:
  - id: grid1
    type: GridModule
    params:
      max_import: 100.0
      max_export: 100.0
      time_series:
        - [0.20, 0.10, 0.5, true]
        - [0.21, 0.11, 0.5, true]
        - [0.22, 0.12, 0.5, true]
        - [0.23, 0.13, 0.5, true]
        - [0.24, 0.14, 0.5, true]
        - [0.25, 0.15, 0.5, true]
        - [0.26, 0.16, 0.5, true]
        - [0.27, 0.17, 0.5, true]
        - [0.28, 0.18, 0.5, true]
        - [0.29, 0.19, 0.5, true]
        - [0.30, 0.20, 0.5, true]
        - [0.31, 0.21, 0.5, true]
        - [0.32, 0.22, 0.5, true]
        - [0.33, 0.23, 0.5, true]
        - [0.34, 0.24, 0.5, true]
        - [0.35, 0.25, 0.5, true]
        - [0.36, 0.26, 0.5, true]
        - [0.37, 0.27, 0.5, true]
        - [0.38, 0.28, 0.5, true]
        - [0.39, 0.29, 0.5, true]
  - id: load1
    type: LoadModule
    params:
      time_series: [
        1.0,
        1.2,
        0.9,
        1.1,
        1.0,
        1.2,
        0.9,
        1.1,
        1.0,
        1.2,
        0.9,
        1.1,
        1.0,
        1.2,
        0.9,
        1.1,
        1.0,
        1.2,
        0.9,
        1.1
      ]
  - id: renewable1
    type: RenewableModule
    params:
      time_series: [
        0.5,
        0.8,
        0.7,
        0.4,
        0.5,
        0.8,
        0.7,
        0.4,
        0.5,
        0.8,
        0.7,
        0.4,
        0.5,
        0.8,
        0.7,
        0.4,
        0.5,
        0.8,
        0.7,
        0.4
      ]
  - id: battery1
    type: BatteryModule
    params:
      min_capacity: 0
      max_capacity: 50
      max_charge: 10
      max_discharge: 10
      efficiency: 0.95
      battery_cost_cycle: 0
      init_soc: 0.5
  # - id: genset1
  #   type: GensetModule
  #   params:
  #     running_min_production: 0
  #     running_max_production: 50
  #     genset_cost: 0.3
