horizon: 24
timestep: 1
components:
  - id: grid1
    type: GridModule
    params:
      max_import: 100.0
      max_export: 100.0
      time_series:
        - [0.2, 0.1, 0.5, true]
        - [0.25, 0.15, 0.6, true]
  - id: load1
    type: LoadModule
    params:
      time_series: [1.0, 1.2, 0.9, 1.1]
  - id: renewable1
    type: RenewableModule
    params:
      time_series: [0.5, 0.8, 0.7, 0.4]
  - id: battery1
    type: BatteryModule
    params:
      min_capacity: 0
      max_capacity: 50
      max_charge: 10
      max_discharge: 10
      efficiency: 0.95
      init_soc: 0.5
  - id: genset1
    type: GensetModule
    params:
      running_min_production: 0
      running_max_production: 50
      genset_cost: 0.3
  - id: unbalanced
    type: UnbalancedEnergyModule
    params:
      loss_load_cost: 10
      overgeneration_cost: 2
